<a href="https://colab.research.google.com/github/Devansh1106/sem5/blob/master/ml/ml_lab/ml_assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write a numpy program to test whether none of the elements of a given array is zero.

In [20]:
import numpy as np
x = np.random.randint(20, size=(10))
print("Array we are checking:",x)
check = 0
for i in range(1, len(x)):
  if x[i] == 0:
    print("The array contains one or more 0's.")
    check = 1
    break
if check == 0:
  print("Array does not contains any zero.")


Array we are checking: [ 1 19 14  2  3  7  9  7 11 17]
Array does not contains any zero.


Write a program to test whether any of the elements of a given array is non-zero.

In [28]:
import numpy as np
x = np.random.randint(10, size=10) # for example of a array of all zero entries, put 0 instead of 10
print("Array we are checking:",x)
check = 0
for i in range(1, len(x)):
  if x[i] != 0:
    print("The array contains one or more nonzero elements.")
    check = 1
    break
if check == 0:
  print("Array does not contains any nonzero.")


Array we are checking: [9 9 3 3 8 5 6 8 2 6]
The array contains one or more nonzero elements.


Write a program to test element-wise for NaN of a given array

In [38]:
import numpy as np
sum = 0
x = np.array([3.0, 45.0, 46.0, np.nan, 1.0, 3.0, np.nan, 6.0, 6.0])
print("Array we are checking:",x)
for i in x:
  if np.isnan(i) == True:
    sum = sum + 1
print("Array contains",sum,"NaN values.")


Array we are checking: [ 3. 45. 46. nan  1.  3. nan  6.  6.]
Array contains 2 NaN values.


Write a program to create an array of 10 zeros,10 ones, 10 fives.

In [45]:
import numpy as np
x1 = np.zeros(10)
x2 = np.ones(10)
x3 = np.ones(10)*5
x = np.concatenate((x1, x2, x3))
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 5. 5. 5. 5.
 5. 5. 5. 5. 5. 5.]


Write a program to create an array of all the even integers from 30 to 70

In [65]:
import numpy as np
x = np.array([])
for i in range(30, 71):
  if i % 2 == 0:
    x = np.concatenate((x, [i]))
print(x)

[30. 32. 34. 36. 38. 40. 42. 44. 46. 48. 50. 52. 54. 56. 58. 60. 62. 64.
 66. 68. 70.]


Write a program to create a 3x3 identity matrix

In [68]:
import numpy as np
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Write a program

In [ ]:
import numpy as np
